"""remove_id_number_from_kyc_details

Revision ID: 4e8e33b53b92
Revises: 922be1c8466e
Create Date: 2026-04-26 10:35:57.923021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8e33b53b92'
down_revision: Union[str, Sequence[str], None] = '922be1c8466e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_details', 'id_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_details', sa.Column('id_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
