"""add_fcm_token

Revision ID: 602527b6291c
Revises: 93cf2ae76b09
Create Date: 2026-04-26 09:06:36.105587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602527b6291c'
down_revision: Union[str, Sequence[str], None] = '93cf2ae76b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fcm_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_fcm_token_device')
    )
    op.create_index(op.f('ix_user_fcm_tokens_user_id'), 'user_fcm_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fcm_tokens_user_id'), table_name='user_fcm_tokens')
    op.drop_table('user_fcm_tokens')
    # ### end Alembic commands ###
