"""rename_kyc_fields_and_optional_coords

Revision ID: 663770499703
Revises: 4e8e33b53b92
Create Date: 2026-04-26 10:56:40.900368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663770499703'
down_revision: Union[str, Sequence[str], None] = '4e8e33b53b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('kyc_details', sa.Column('district', sa.String(), nullable=True))
    op.add_column('kyc_details', sa.Column('landmark', sa.String(), nullable=True))
    
    # Migrate data
    op.execute("UPDATE kyc_details SET district = address_line1")
    op.execute("UPDATE kyc_details SET landmark = address_line2")
    
    # Set district to NOT NULL after migration
    op.alter_column('kyc_details', 'district', nullable=False)
    
    op.alter_column('kyc_details', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('kyc_details', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('kyc_details', 'address_line2')
    op.drop_column('kyc_details', 'address_line1')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_details', sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('kyc_details', sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('kyc_details', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('kyc_details', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('kyc_details', 'landmark')
    op.drop_column('kyc_details', 'district')
    # ### end Alembic commands ###
